name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: queue-master
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/queue-master/queue-master/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - uses: actions/checkout@v2


    - run: touch starting_test_uses-setup-java_26
    - run: rm starting_test_uses-setup-java_26
    - uses: actions/setup-java@v1
      with:
        java-version: '8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

 
    #
    #
    # Build
    - run: touch starting_test_Buildjarfiles_36
    - run: rm starting_test_Buildjarfiles_36
    - name: Build jar files
      run: ./scripts/build.sh

    #
    #
    # Unit test
    - run: touch starting_test_Rununittests_42
    - run: rm starting_test_Rununittests_42
    - name: Run unit tests
      run: ./test/test.sh unit.py

    #
    #
    # Component test
    - run: touch starting_test_Runcomponenttests_48
    - run: rm starting_test_Runcomponenttests_48
    - name: Run component tests
      run: ./test/test.sh component.py

    #
    #
    # Upload coverage results to coveralls
    - run: touch starting_test_SubmitCoveralls_54
    - run: rm starting_test_SubmitCoveralls_54
    - name: Submit Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: docker run --rm -v ${HOME}/.m2:/root/.m2 -v ${PWD}/test/..:/usr/src/mymaven -w /usr/src/mymaven maven:3.2-jdk-8 mvn -DrepoToken=${COVERALLS_TOKEN} -DserviceJobId=${GITHUB_RUN_ID} -Dbranch=${GITHUB_REF} -DpullRequest=${GITHUB_HEAD_REF} -DserviceName=GITHUB verify jacoco:report coveralls:report

    #
    #
    # Push to dockerhub
    - run: touch starting_test_PushtoDockerHub_63
    - run: rm starting_test_PushtoDockerHub_63
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        path: docker/queue-master
        dockerfile: docker/queue-master/Dockerfile
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: rat check
      if: always()
      run: |
         if [ -f /home/runner/work/queue-master/queue-master/target/rat.txt ]; then cat /home/runner/work/queue-master/queue-master/target/rat.txt; fi
    - name: Check script file exists and execute
      if: always()
      run: |
        [ -f .github/workflows/script.py ] && python .github/workflows/script.py
        [ -f /home/runner/work/queue-master/queue-master/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/queue-master/queue-master/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},queue-master,${GITHUB_WORKFLOW}" > /home/runner/work/queue-master/queue-master/optimizing-ci-builds-ci-analysis/job.csv
    - name: Checkout to destination CI-analyzes repo
      uses: actions/checkout@v3
      if: always()
      with:
        path: queue-master
        ref: '1686856134-548a464'
        repository: 'UT-SE-Research/ci-analyzes'
        token: '${{ secrets.API_TOKEN_GITHUB }}'
        persist-credentials: true
    - name: Copy files to push to another directory
      if: always()
      run: |
        mkdir -p queue-master/queue-master/.github/workflows/main/test
        cp -rvT optimizing-ci-builds-ci-analysis queue-master/queue-master/.github/workflows/main/test
    - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1686856134-548a464/queue-master/.github/workflows/main/test
    - name: Pushes analysis to another repository
      if: always()
      working-directory: queue-master
      run: |
        commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
        git config --global user.name 'UT-SE-Research'
        git config --global user.email '${{ secrets.EMAIL }}'
        git add .
        git commit -m $commit_message
        while ! git push origin 1686856134-548a464; do
          git pull --rebase origin 1686856134-548a464
          sleep $((RANDOM % 5 + 1))
        done