name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: queue-master
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/queue-master/queue-master/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - uses: actions/checkout@v2


    - run: touch starting_test_uses-setup-java_26
    - run: rm starting_test_uses-setup-java_26
    - uses: actions/setup-java@v1
      with:
        java-version: '8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

 
    #
    #
    # Build
    - run: touch starting_test_Buildjarfiles_36
    - run: rm starting_test_Buildjarfiles_36
    - name: Build jar files
      run: ./scripts/build.sh

    #
    #
    # Unit test
    - run: touch starting_test_Rununittests_42
    - run: rm starting_test_Rununittests_42
    - name: Run unit tests
      run: ./test/test.sh unit.py

    #
    #
    # Component test
    - run: touch starting_test_Runcomponenttests_48
    - run: rm starting_test_Runcomponenttests_48
    - name: Run component tests
      run: ./test/test.sh component.py

    #
    #
    # Upload coverage results to coveralls
    - run: touch starting_test_SubmitCoveralls_54
    - run: rm starting_test_SubmitCoveralls_54
    - name: Submit Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: docker run --rm -v ${HOME}/.m2:/root/.m2 -v ${PWD}/test/..:/usr/src/mymaven -w /usr/src/mymaven maven:3.2-jdk-8 mvn -DrepoToken=${COVERALLS_TOKEN} -DserviceJobId=${GITHUB_RUN_ID} -Dbranch=${GITHUB_REF} -DpullRequest=${GITHUB_HEAD_REF} -DserviceName=GITHUB verify jacoco:report coveralls:report

    #
    #
    # Push to dockerhub
    - run: touch starting_test_PushtoDockerHub_63
    - run: rm starting_test_PushtoDockerHub_63
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        path: docker/queue-master
        dockerfile: docker/queue-master/Dockerfile
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'optimizing-ci-builds'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1673993621'
        target-directory: 'queue-master/.github/workflows/main/test'
